name: Pages

on:
  workflow_dispatch:
  push:
    branches:
      - dev
    paths:
      - docs/**
      - package.json
      - .github/workflows/main.yml

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Use Node.js LTS
        uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: npm
      - name: Install Dependencies
        run: npm i --force
      - name: Build
        run: npm run docs:build
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./docs/.vitepress/dist

  deploy:
    if: github.ref == 'refs/heads/dev'
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
